language: python

sudo: false

env:
  - LUA="lua 5.2"

branches:
  only:
    - master

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate
  - luarocks install busted

script:
  - busted src/test/lua/
