name: busted

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  busted:
    runs-on: ubuntu-latest

    env:
      LUA_VERSION: 5.2
      LUAENV: luaenv

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install busted
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/luarocks/hererocks
          python -m hererocks ${LUAENV} -l ${LUA_VERSION} -r latest
          source ${LUAENV}/bin/activate
          luarocks install dkjson
          luarocks install busted
          luarocks install luacov
          luarocks install luacov-multiple --server https://oocytanb.github.io/rocksrepo/
          lua -v
          busted --version

      - name: Test with busted
        run: |
          source ${LUAENV}/bin/activate
          busted -c src/

      - name: Show coverage summary
        run: |
          sed -n -E '/^File.+Hits.+Missed.+Coverage$/,$p' luacov.report.out
